export const refs = {
  burgerBtnOpenMenu: document.querySelector('.icon-burger'),
  burgerBtnCloseMenu: document.querySelector('.icon-close'),
  headerMenuContainer: document.querySelector('.header-menu-container'),
  loaderOverlay: document.querySelector('.loader-in'),
  modalForm: document.querySelector('.feedback-mod'),
  stars: document.querySelectorAll('.star-rating path'),
  nameInput: document.querySelector('.feedback-mod [name="name"]'),
  messageInput: document.querySelector('.feedback-mod [name="message"]'),
  modalOverlayArtists: document.querySelector('.modal-overlay-artists'),
  closeBtn: document.querySelector('.close-btn-mod'),
  feedbackBtn: document.querySelector('.feedback-btn'),
  menuAnchorAbout: document.querySelector('#menu-anchor-about'),
  menuAnchorArtists: document.querySelector('#menu-anchor-artists'),
  menuAnchorReviews: document.querySelector('#menu-anchor-reviews'),
  artistsGrid: document.getElementById('artists-card-id'),
  loadMoreBtn: document.getElementById('load-more-btn'),
  loader: document.querySelector('.modal-loader'),
  modalOverlay: document.querySelector('.modal-overlay'),
  body: document.querySelector('body'),
  closeModalBtn: document.querySelector('.close-btn'),
  titleName: document.querySelector('.modal-info-title'),
  aboutArtist: document.querySelector('.modal-info-card'),
  modalAlboms: document.querySelector('.modal-alboms'),
  artistsSection: document.querySelector('#artists-card-id'),
};
